export const mapProfileToForm = (data = {}) => ({
  rank: data.rank || "",
  division: data.division || "",
  firstName: data.firstName || "",
  lastName: data.lastName || "",
  username: data.username || "",
  birthDate: data.birthDate || "",
  fullAddress: data.fullAddress || "",
  email: data.email || "",
  phone: data.phone || "",
  emergencyContactName: data.emergencyContactName || "",
  emergencyContactPhone: data.emergencyContactPhone || "",
  education: data.education || "",
  position: data.position || "",
  medicalhistory: data.medicalhistory || "",
  notes: data.notes || "",
  avatar: data.avatar || "",
});

export const editableKeys = [
  "rank",
  "division",
  "firstName",
  "lastName",
  "username",
  "birthDate",
  "fullAddress",
  "email",
  "phone",
  "emergencyContactName",
  "emergencyContactPhone",
  "education",
  "position",
  "medicalhistory",
  "notes",
];
